client/src/components/Home/TravelGuides.jsx
client/src/pages/TravelGuidesProfiles.jsx

solved issue #183. Added the view profile functionality on home page guide section which takes user to the detailed profile of the guide on the guides page directly as follows:

Solved Issue #183 - added view profile functionality to home page guides section

---

client/src/components/GoToTopButton.jsx

**Title:**  
Fixed Automatic scroll to top when route is changed.
No automatic scroll to top was present when i change the route, every time i have to click scroll to top button,
like if i scroll home and move to any other page, that page is also already scrolled, so now on any route change page will start from top always.

Fixed Automatic scroll to top when route is changed. (issue 219)

---

client/package.json
client/src/pages/TicketBooking.jsx

**Title:**  
This PR fixes past date ticket booking issue. 
Earlier, when the user selects a past date for ticket booking, the application allows booking a ticket for a past application. However, I have now disabled the option to select a past date, which prevents users from choosing a date before today.
I have also solved the issue for the return date. If a user now selects some date as departure date, then they must choose a date after it for return date.
fixed #252

Fixed past date ticket booking issue

---

client/src/components/TripExpenseCalculator/ExpenseCalculator.jsx
client/src/components/TripExpenseCalculator/ExpenseInputRow.jsx
client/src/pages/TripCalculator.jsx

**Title:**  
[UI] Enhance Legend Text Contrast in Trip Expense Pie Chart
This pull request improves the color contrast of the legend text in the Trip Expense Pie Chart. Previously, labels like "Accommodation", "Activities", "Food", "LocalTransport", "Miscellaneous", and "Transport" were difficult to read due to light font colors blending with the light pink background. The changes ensure better accessibility and readability by adjusting the page background colors to darker shades while keeping them visually consistent with the chart.
#337

[UI] Enhance Legend Text Contrast in Trip Expense Pie Chart

---

client/src/pages/Hotels.jsx

**Title:**  
Fix : Hotels page hero section title color
changed font color of hotels page hero section title from 
Fixes #406 
Before :
after :

Fix : Hotels page hero section title color

---

client/src/components/Custom/Footer.jsx
client/src/pages/Contributors.jsx

**Closes #333**
---
- Dynamically fetches contributors from:
https://api.github.com/repos/Adarsh-Chaubey03/TravelGrid/contributors
- Displays each contributor with:
- 🖼️ Avatar
- 👤 GitHub username
- 🔗 Link to profile
- 📊 Number of contributions
- Toggle button to show/hide merged pull requests for each contributor.
- Only successfully **merged PRs** are shown.
- Titles are shortened if too long and link directly to the GitHub PR.
- Fully responsive grid layout using Tailwind CSS.
- Gradient background: `from-purple-900 via-blue-900 to-indigo-900`.
- Stylish card hover animations (scale, blur, shadow).
- Text and elements themed using `text-pink-200` and `bg-white/10`.
- Replaced SVG path with a **YouTube-like play icon** to a **contributors icon**.
- Floating pink circular button now …

Added merged PR toggle feature on contributors page

---

client/src/pages/TicketBooking.jsx

**Title:**  
Fix Typo: Change "buss" to "bus" using PluralMap
This pull request resolves a minor typo in the TicketBooking.jsx file where the term "buss" was incorrectly used.
The correction replaces it with "bus", and the PluralMap is used to ensure consistency across label handling.
Fixes #447
Closes #447
The typo in the route label "buss" was due to directly appending 's' to the `travelType`, like this:
```jsx
Search {travelType.charAt(0).toUpperCase() + travelType.slice(1)}s
```
This caused incorrect pluralization (e.g., "buss" instead of "buses").
To fix this, I introduced a `pluralMap` object to handle correct plural forms:
```js
const pluralMap = {
bus: "Buses",
train: "Trains",
flight: "Flights"
};
```
Then updated the JSX to use:
```jsx
Search {pluralMap[travelType] || …
```

Fix 'buss' typo using PluralMap in TicketBooking page

---

client/src/App.jsx
client/src/components/GoToTopButton.jsx

**Title:**  
Go to top button fixed
Earlier this button was overlapping the chat icon as i had mentioned in my issue #445  but was refactored in some commit
but this made the icon appear on the left which was not pleasing this commit shifts it to right along other icons
Fixed version

gototop button properly fixed no overlap and in line

---

client/src/components/Custom/Footer.jsx

This PR enhances the user experience by making the address in the Contact Info section interactive. Previously, the address (123 Travel Street, Adventure City, AC 12345) was static text. Now, clicking the address opens its location in Google Maps in a new tab.
- feature enhancement
- Improves UX by making it easier for users to locate the physical address.
- Aligns with common web practices for contact information.
- [✓ ] My code follows the project style guidelines
- [ ✓] I have performed a self-review of my code
- [✓ ] I have commented my code, particularly in hard-to-understand areas
- [✓ ] My changes generate no new warnings or errors
Please note that the current address (123 Travel Street, Adventure City, AC 12345) is a placeholder and not a real location. Make sure to replace it …

Make Address in Contact Info Clickable to Open in Google Maps

---

client/src/components/Custom/Navbar.jsx

**Title:**
**fix(navbar): highlight Booking, Support, Tools tab when dropdown subpages are active**
---
This PR updates the `Navbar.jsx` logic to correctly highlight the parent tabs (Booking, Support, Tools) when any of their respective dropdown subpages are active. Previously, only the exact route would trigger highlighting, which caused confusion when navigating subpages.
---
---
---
Fixes: *No issue number attached (direct UI fix)*
Fixed #463 
---
* This change ensures better UX by keeping the navbar state consistent with current routes, even if the user is on a nested subpage.

fix: highlight Booking, Support, Tools tab when dropdown subpages are active #463

---

client/src/ScrollToTOp.jsx

**Title:**  
feat: add animated ScrollToTop button with dark mode support
- Added floating scroll-to-top button
- Appears after 300px scroll depth
- Smooth scroll animation (300ms)
- Dark/light mode compatible
- Accessible (ARIA labels, keyboard nav)
- Mobile-responsive positioning
Closes #625 
1. Scroll down 300px → button appears
2. Click → verify smooth scroll
3. Toggle dark mode → check styling
4. Tab navigate → confirm focus
- Uses `window.scrollTo({behavior: 'smooth'})`
- Tailwind classes for animations
- Z-index: 40 (above other floats)

feat: add animated ScrollToTop button with dark mode support

---

client/src/components/Custom/CustomCarousel.jsx

Add cursor pointer to the guides card arrow buttons.
I initially thought the guide card images were oval-shaped on my side, but after checking from another account, they appeared correctly shaped. Therefore, I focused on updating the arrow buttons in the guides card slider to use a pointer cursor for better user experience.
fixes #749
Let me know if you’d like to merge this change or not.

Fix: Add cursor pointer to guides card arrow buttons

---

client/src/pages/MoodBoardPage.jsx

**Title:**  
Remove Duplicate Footer from AI-Powered Travel Mood Board Page
---
This pull request fixes the issue where the AI-Powered Travel Mood Board page displayed two footers simultaneously, creating redundancy and disrupting the visual flow of the page. The duplicate footer has been removed to maintain a clean and consistent layout in line with the overall theme.
---
Fixes Issue: #805 
Before--
After--

Remove Duplicate Footer from AI-Powered Travel Mood Board Page

---

client/src/pages/HotelBookingForm.jsx

**Title:**  
Fix the guests button. Added + and - buttons
Initially, there is a dropdown, which contains static count of guests. For every hotel, the max number of guests are displayed as 6. I modified this feature by adding + and - buttons to adjust the number of guests.
closes #854

Fix the guests button. Added + and - buttons

---

client/src/components/Home/TravelGuides.jsx
client/src/pages/TravelGuidesProfiles.jsx

**Title:**  
Consistent Home page's guide section + seperated pet guides
This PR resolved the inconsistencies in the number of guides shown in the guide page and home page, and it separates the pet guides and non-pet guides in the guide page for easy access to both. and it also introduces a new pet guide as earlier there were only 2 pet guides.
fixed #883 
Added missing guides in home section guides
https://github.com/user-attachments/assets/dc168a71-9b86-4c1c-88fe-b4a473218f82
Separated pet and non-pet guides
https://github.com/user-attachments/assets/3da0b728-aed7-4233-b5ca-64a2344cda85

Consistent Home page's guide section + seperated pet guides

---

client/src/components/LanguageSelector.jsx
client/src/context/LanguageContext.jsx

This PR resolves the issue of duplicate language codes (`IN`) in the language selector dropdown.  
Previously, multiple entries appeared identical, making it unclear which language was being selected.  
#Changes Made
- Updated dropdown labels to display unique and descriptive language names.  
Example: `Hindi - IN`, `Tamil - IN`, `Bengali - IN`, etc.  
- Ensured proper localization keys are mapped to respective languages.  
- Each language option is now shown with its proper name and code.  
- Users can clearly identify which language they are selecting.  
- Improved user experience by removing ambiguity in language selection.  
- Better accessibility and usability for non-English speakers.  
#Screenshots
**Before:**  
Multiple options labeled only as `IN`.  
**After:**  
Each option …

Updated language selector dropdown to show unique and descriptive labels (Fixes #926)

---

client/package-lock.json
client/src/pages/GitHubStats.jsx
client/yarn.lock

**Title:**  
Fix GitHubStats background transparency in About page
Removed the background color from the GitHubStats component to make it transparent and consistent with the About page background. The section now properly inherits the page's background styling instead of having its own opaque background by setting `bg-transparent` class.
Fixes #1125 
**Before**
---
**After**
The change ensures visual consistency across the About page by removing the opaque background from the Project Stats section using `bg-transparent` class, allowing it to blend seamlessly with the page's existing background styling and theme. The component now properly inherits the parent page's background instead of creating

Fix GitHubStats background transparency in About page

---

client/src/pages/Trips.jsx

**Title:**  
Improve trips page light mode UI with better background, button styling and  icons.
Updated the Trips page UI for light mode to improve readability :
- Updated background color and text colors in all elements for better visibility. 
- Making icons and text darker in light mode.
- Fixing button hover effects and some minor typos. 
- Keeping design consistent in both light and dark mode.
Closes #1112 
Updated Trips Light mode:
N/A

Improve Trips Page Light mode UI with better background handling, icons, and button styling

---

client/src/pages/PackageDetails.jsx

**Title:**  
Modify font colors in the packages page
Initially, the font is not visible in light mode.  I modified font colors in the packages page with the color that is visible in light and dark modes.
Closes #1147 
Before Changes:
After Changes:
Now the font is visible in both light and dark mode.

fix the text color in packages page

---

client/src/components/Custom/Navbar.jsx

**Title:**  
Enhance navbar dropdown arrow and text color
This PR improves the Navbar dropdown behavior and visibility:  
- Rotates the dropdown arrow (chevron) to indicate open/close state.  
- Updates the dropdown arrow (chevron) text color in light mode for better contrast.  
- Adds smooth slide and fade animation for dropdown menu items. 
- Add cursor pointer to clickable button.
Closes #1186  
N/A

Enhance Navbar dropdown arrow and text color

---

client/src/components/Custom/Footer.jsx

**Title:**  
The footer extra space has been removed and looks fine as checked on the local machine and tested it.
The extra space the came under the footer has been removed from the website. Solved the issue #1232 Footer with Extra space.
Fixes #1232 
The space has been removed
Loved to work on this issue. @gssoc25

FOOTER EXTRA SPACE REMOVED

---

client/src/components/Custom/Footer.jsx

Fix issue #1302 
> Refactored Footer component styles to conditionally apply text colors and improve dark mode compatibility. Removed hardcoded gray text classes and replaced them with dynamic classes based on the isDarkMode state.

Update Footer styles for dark mode support

---

README.md
client/src/pages/Signup.jsx

Description
This PR adds a Contributors section to the README.md to recognize and showcase all contributors, making the repository more welcoming for new contributors.
Current Problem
The README.md currently lacks a Contributors section to recognize contributors and guide new ones.
Proposed Solution
Add a Contributors section at the end of README.md
Include an auto-generated contributor badge via [contrib.rocks](https://contrib.rocks/)
Update Table of Contents to include this new section
Keep all existing content intact and improve formatting where necessary
Benefits
Recognizes contributors and shows appreciation
Makes the repository more welcoming for new contributors
Improves documentation readability and structure
Close issue #1331

Add Contributors Section to README

---

client/src/pages/Rentals.jsx

Fixed Heading visibility in Light mode of rental page

---

client/src/components/Contact.jsx

- Closes #1309 
This PR update removes the manually set background color in the contact section that was overriding the site’s theme color
- Removed contact section background color that conflicted with the theme.
- No other functional or styling changes.
There are currently two contact pages in the repository.  extra contact page be removed, keeping only the **Contact.jsx** component linked to the /contact URL.

Fix: remove overriding background color in Contact 

---

client/src/components/Custom/Footer.jsx

fixes #1358
- footer is matching with the website theme in the light mode

fixed the footer background in the light mode
