Adarsh-Chaubey03/TravelGrid

client/src/components/Custom/Navbar.jsx, client/src/components/Home/FeaturedPackages.jsx, client/src/components/Home/TravelGuides.jsx
=> UPDATED SOME CODE

client/src/components/Custom/Footer.jsx
**Title:**  
Add Footer with Newsletter Subscription and Toast Notifications
This PR adds a responsive `Footer` component featuring:
- Newsletter subscription form with validation
- Success and error toast notifications with auto-dismiss after 4 seconds
- Four-column layout: Logo/description, Quick Links, Info, and Newsletter
#1 
Do we need to match the provided design/image exactly, or is slight flexibility in layout and spacing acceptable?
=> Enhanced Footer with newsletter subscription and toast notifications

client/src/main.jsx, client/src/pages/TicketBooking.jsx, package-lock.json
**Title:**  
Added the Ticket Booking Page to the Project
A new ticket booking page has been added with the following features:
- **Travel type:** Select between Flight, Train, Bus, or Cab
- **From:** Departure city input
- **To:** Destination city input
- **Date:** Date picker for travel
- **Number of passengers:** Input for passenger count
The page features a modern, light UI with a gradient background (`from-blue-50 to-pink-50`), matching the website’s theme. The form is interactive and user-friendly, and is accessible via the Navbar.
N/A
- The booking form is fully responsive and matches the overall site design.
- The page is accessible via the Navbar as “Ticket.”
- Further backend integration or validation can be added as needed.
=> Added the ticket booking page with similar UI

client/package-lock.json, client/src/main.jsx
When navigating to the /guides route, the application throws the following error:
Uncaught ReferenceError: TravelGuidesCarousel is not defined.
fixes #43 
Please @Adarsh-Chaubey03 check and merge the PR.
=> uncaught reference error solved

client/src/main.jsx, client/src/pages/HotelBookingPage.jsx
Reverts Adarsh-Chaubey03/TravelGrid#48
=> Revert "Update"

client/src/App.jsx, client/src/components/Custom/Footer.jsx, client/src/components/Custom/Navbar.jsx, client/src/components/ErrorHandle/ServerError.jsx, client/src/pages/Contact.jsx, client/src/pages/Home.jsx, client/src/pages/NotFound.jsx, client/src/pages/TicketBooking.jsx
**Title:**  
Refactor: Implement Global Layout with Consistent Navbar and Footer
This PR fixes the issue where several pages were missing the Navbar and Footer components. The implementation refactors the main `App.jsx` component to serve as a global layout wrapper that includes the Navbar and Footer for all routes rendered through the router's `Outlet`. This ensures a consistent UI across all pages and eliminates code duplication.
Key changes:
- Moved Navbar and Footer to the App.jsx component as global layout elements
- Removed redundant Navbar and Footer imports from individual page components
- Added proper flexbox structure to maintain layout consistency
- Ensured the footer stays at the bottom with flex-grow content
- Fixed page structure for better user experience
Fixes #56 - …
=> Refactor: Implement Global Layout with Consistent Navbar and Footer

client/src/components/Custom/Navbar.jsx, client/src/data/hotels.js, client/src/main.jsx, client/src/pages/HotelDetails.jsx, client/src/pages/Hotels.jsx
**Title:**   Add Hotels Web Page  
This pull request adds a new Hotels web page to the project.
- I added a "Hotels" button in the website header.
- When the button is clicked, it navigates to a new Hotels page.
- The Hotels page displays a list of hotels using cards and is fully responsive.
- The structure and styling follow the existing project layout for consistency. 
Closes #35 
This updates makes website more attractive and usefull.
I hope you like this.
Regards
=> ADD HOTELS WEB PAGE

client/src/components/Custom/Navbar.jsx, client/src/main.jsx, client/src/pages/Home.jsx, client/src/pages/Login.jsx, client/src/pages/Signup.jsx
**Title:**  
Added Log in and Sign Up Page with responsive UI.
Introduced completely functional and styled Signup and Login pages with React and Tailwind CSS. Both pages are:
- Created with a uniform UI look.
- Completely responsive for big screens and mobile.
- Have smooth visual components and input validation (such as password strength verification).
✔ New Feature
- ✔  My code follows the project style guidelines
- ✔ I have performed a self-review of my code
- ✔  I have commented my code, particularly in hard-to-understand areas
-  I have made corresponding changes to the documentation
- ✔  My changes generate no new warnings or errors
-  I have added tests that prove my fix is effective or that my feature works
-  New and existing unit tests pass locally with my changes
# …
=> Login and Sign Up page implementation

client/index.html, client/src/pages/HotelDetails.jsx, client/src/pages/Hotels.jsx, client/src/pages/TicketBooking.jsx
**Title:**  
Removal of Dual footer from hotels and hotels Booking pages and more better Title
The hotels and hotel booking pages earlier rendered two footer and nav corrected it properly and give the website a proper title
- [x ] Bug fix
- [ x] Refactor
Closes #57
=> Removal of Dual footer from hotels and hotels Booking pages and more better Title

client/src/pages/TravelPackages.jsx
**Title:**  
Added filters to packages page
The Travel Packages page now includes a robust filtering feature that enables users to easily narrow down available travel packages based on their preferences for minimum rating and maximum price. This enhancement improves user experience by allowing quicker access to relevant packages that meet budget and quality expectations.
#122
=> Added filters to Packages page

README.md, Server/.gitignore, Server/config/db.js, Server/controller/authController.js, Server/index.js, Server/models/user.js, Server/package-lock.json, Server/package.json, Server/routes/authRoutes.js
This PR sets up the initial backend architecture for TravelGrid, providing the foundational structure for all upcoming server-side features.
ISSUE NO. #83 
**What's included:**
1. Express.js server setup
2. MongoDB connection via Mongoose
3. Environment variable handling (dotenv)
4. auth routes with signup & login support
5. JWT-based user authentication flow
6. Modular folder structure (controllers, routes, models, middleware, config)
7. CORS and error-handling middleware
README with setup instructions
This setup enables future development of features like trip booking, user profiles, and admin modules.
**Type of Change**
**Checklist :-**
Related Issues
Closes #83  – Backend Setup Initialization (or replace with actual issue number)
**Screenshots**  (if applicable)
Not applicable for …
=> Feature/backend init user setup ( Backend Initialized with Auth, Routes, and MongoDB Connection )

client/package-lock.json, client/package.json, client/src/components/Home/TravelGuides.jsx
**Title:**  
In the Travel Guide file i have made some changes that now the user can move and see the travel guide with moving the button's 
closes: #154
=> Added Slider to the guide

client/src/App.jsx, client/src/main.jsx
=> Resolved Build logs and all file error to ensure preview.

client/src/components/Custom/Navbar.jsx, client/src/pages/Login.jsx
Solved issue #178- Added functionality to login button on navbar
=> Solved issue #178- Added functionality to login button on navbar

client/src/pages/TravelPackages.jsx
Pull request on issue no #210 
**Title:**  
Added Travel Packages to improve Customer response and engagement 
Added 6 more destination packages
=> Added Travel Packages

client/src/components/GoToTopButton.css, client/src/components/GoToTopButton.jsx
**Title:**  
Enhance scroll-to-top button with UI improvements
- Improved scroll-to-top button design.
- Added smooth scroll behavior.
- Updated button color and hover effect.
- Added visibility toggle using CSS.
fixes #212 
N/A
Improved button UI for better visibility and user experience without major layout changes.
=> Enhance: Scroll to Top Button UI with hover, visibility, and color changes.

client/src/pages/TicketBooking.jsx, client/src/pages/TravelPackages.jsx
Fixed critical navbar overlapping issue and mobile responsiveness problems in the TicketBooking page. Merged from a previously stable version and implemented additional mobile-specific improvements to ensure proper functionality across all devices.
**Key Changes:**
- **Fixed navbar overlap**: Added proper top padding (`pt-25`) to prevent navigation bar from covering the main title "Book Your Perfect Trip"
- **Mobile responsiveness fixes**: Resolved mobile version issues that were causing incorrect display and functionality
- **Version stability**: Merged from a previously working version to ensure stable functionality
- **Enhanced UI/UX**: Improved overall user experience with better spacing and responsive design
- **Typography improvements**: Updated title styling with responsive text …
=>  Fix navbar covering title issue and mobile responsiveness in TicketBooking page

client/src/components/Custom/Navbar.jsx
**Title:**  
Enhance Navbar UI: Add Sidebar Animation & Polished Design
This PR improves the user interface of the Navbar component. Key changes include:
-Enhanced desktop nav styling with better hover states and active link indication.
-Fully functional and responsive mobile sidebar with slide-in/out animation.
-Added a semi-transparent overlay when the mobile menu is active.
-UI now aligns better with the overall visual theme of the project.
These changes make the navigation experience more interactive and visually appealing.
Closes #218 
Let me know if you'd like to tweak the animations or adjust the gradient colors to match other pages.
=> NavBar Elements hover fixed

client/src/components/Custom/Footer.jsx, client/src/components/Custom/Navbar.jsx
**Title:**  
Remove Duplicate Twitter Icon in Footer
This PR removes the extra Twitter icon from the footer component to reduce visual clutter and maintain consistency.
Closes #232 
Before :
After :  
Let me know if you'd like to make any UI improvements here
=> Fix footer twitter icon

client/src/components/Custom/Navbar.jsx
**Title:**  
Responsive Navbar: Menu options not toggling properly on small screens
In the responsive view (on smaller screens), the navbar menu options are not displayed properly. They appear misaligned, cluttered, or visually broken, which makes navigation difficult and impacts user experience.
Fixes #177 , Closes #177
=> fix-responsive-navbar

client/src/assets/defaultprofile.svg, client/src/context/AuthContext.jsx, client/src/pages/Dashboard.jsx
##Title:
Add Edit Profile Feature with Default Avatar Handling
##Description
This PR implements the Edit Profile functionality on the dashboard as described in issue #225.
Added an "Edit Details" button to allow users to update their name and email.
Displayed a default avatar image when the user has not uploaded one.
##Type of Change
New feature
##Checklist
My code follows the project style guidelines
I have performed a self-review of my code
I have commented my code where necessary
My changes generate no new warnings
##Related Issues
Closes #225
##screenshot
=> Add Edit Profile Feature with Default Avatar Handling

client/src/components/Custom/Footer.jsx, client/src/main.jsx, client/src/pages/Trips.jsx
Solved Issue #185  -added trips page to the app as follows:
=> Solved Issue#185-added trips page to the app

client/src/pages/TicketBooking.jsx
**Title:**  
Added ticket booking initiating section before showing confirmation
Earlier when search flight button was pressed, it immediately booked the flight instead of showing the option to book and without showing details like price of flight.
fixed #176 
Before
After
=> Added ticket booking initiating section before showing confirmation

client/package-lock.json, client/package.json, client/src/App.jsx, client/src/context/AuthContext.jsx, client/src/main.jsx, client/src/pages/Login.jsx, client/src/pages/Signup.jsx
**Title:**  
🔧 Fix: Auth Flow and Navbar Visibility Issues (#221)
This PR resolves Issue #221, which involved several critical problems in the authentication and frontend state flow. Below is a structured summary of the work done:
> Implemented a complete AuthContext setup with:
`login, signup, and logout functions`
`automatic localStorage session restoration`
`Ensured persistent login state is tracked correctly across reloads`
`Navbar now dynamically updates based on login state (e.g., Dashboard/Logout appear after login)`
`Fixed blank screen issue that occurred due to useAuth being used outside AuthProvider`
`Added protected route logic and ensured it wraps pages like /dashboard`
`Integrated React Hot Toast:`
`Shows success/failure notifications on login, signup, and logout`
`Appears …
=> 🔧 Fix: Auth Flow and Navbar Visibility Issues (#221)

client/src/pages/TravelGuidesProfiles.jsx, client/src/pages/styles/TravelGuidesCarousel.css
**Title:**  
Improve guides layout by changing layout and change button style.
- Adjusted padding and margin of the guide titles for better responsiveness across mobile devices.
- Changed the button design to better match the overall look of the website.
- Improved the guides page text content for a more professional and polished tone.
- Fixed the issue where the title was overlapping by adding proper margin and padding.
Fixes #214 
N/A
Let me know if any further design changes are needed. I'm happy to make updates!
=> Improve Guides Page Layout and Button Style

client/src/data/PackageData.js
**Title:**  
Resolved mismatch issue of duration and day-wise itinerary
Earlier content for all day-wise itinerary was similar, so the packages having duration of 4 and 7 days were also having day-wise itinerary of 5 days, but now it is changed to match the duration of package.
fixed #282
=> Resolved mismatch issue of duration and day-wise itinerary

Server/controller/authController.js, Server/package-lock.json, Server/package.json, client/package-lock.json, client/package.json, client/postcss.config.js, client/src/index.css, client/tailwind.config.js
**Title:**  
Fix: Signup and Login validation and JWT handling
This PR fixes issues in the signup and login authentication flow.
- Added proper email normalization during registration and login.
- Improved error handling for missing fields.
- Integrated JWT handling using environment variables securely.
- Fixed password hashing logic using bcrypt.
- Ensured clean JSON responses for success and error cases.
Closes #306
---
=> Fix: Signup/Login validation and JWT handling

LEARN.md
This PR adds a Styling Consistency section to the Learn.md file (which serves as the project's contributing guide). It suggests using a single styling method across the project — preferably Tailwind CSS — to avoid confusion and improve code maintainability.
This update introduces styling guidelines under the contribution guidelines section in `Learn.md`.  
It aims to keep the codebase clean by encouraging the use of a single styling method across all components.
Fixes #256 
N/A
Let me know if you'd prefer renaming learn.md to contributing.md for better clarity — I’d be happy to help update that too.
=> Docs: Add Styling Consistency section in Learn.md.

Server/models/feedback.js, Server/models/forumPost.js, Server/models/hotel.js, Server/models/ticketBooking.js, Server/models/travelGuide.js, Server/models/travelPackage.js
**Title:**  
Add/Update Mongoose Models for TravelGrid Backend
This commit introduces/updates several Mongoose models in the backend to support core features of the TravelGrid application. The models define the schema and structure for key entities such as users, hotels, travel packages, feedback, forum posts, ticket bookings, and travel guides. These models are essential for database operations and ensure data consistency throughout the application.
=> Create db  models for every feature

client/src/components/Home/HeroSection.jsx, client/src/pages/NotFound.jsx
**Title:**  
Margin and paddding issues in homepage hero section 
Fixes #318
=> fixed margin and padding issue in home page issue #318

Server/controller/saveController.js, Server/index.js, Server/models/user.js, Server/routes/saveRoutes.js, client/src/context/AuthContext.jsx, client/src/pages/Hotels.jsx, client/src/pages/SavedPlaces.jsx
**Title:**  
✨ Add Save Places Feature with Dashboard Integration
This PR introduces a Save Places feature allowing authenticated users to like hotels and save them to their dashboard. The data is stored in the user's savedPlaces array in MongoDB.
Key features:
`Added save button to hotel cards`
`Only logged-in users can save places`
`Places saved: placeId, name, description (image skipped for now)`
`Created Saved Places page inside Dashboard`
`Added delete functionality to remove saved places`
`Used React Hot Toast for feedback on actions`
Currently, hotel data is fetched from a static hotels.js file. If assigned, I would love to store hotel data in MongoDB and make the display dynamic.
Closes #323
https://github.com/user-attachments/assets/351e905e-262e-40b7-b555-334e635ed9b0
This …
=> ✨ Add Save Places Feature with Dashboard Integration

Server/.env.example, Server/models/user.js, Server/package-lock.json, Server/package.json, client/src/context/AuthContext.jsx, client/src/pages/Signup.jsx
**Title:**  
This pull request fixes the issue with the signup page which was previously not functioning as expected. The changes include:
-Fixed form submission logic
-Ensured proper input validations
-Connected the form correctly with the backend API 
-Tested the flow locally to ensure smooth user experience
- [ x] Bug fix
Let me know if any changes are needed. Looking forward to your feedback! 🚀
=> Fix : SignUp page issue(#362)

client/src/components/Custom/Navbar.jsx, client/src/components/DiscoverCard.jsx, client/src/pages/DiscovermoreDestination.jsx
**Title:**  
Resolved the text Color problem and Header gap problem as told in issue #419 
gap reduced between header content and in discover added tailwind properly
- [2 ] Refactor
=> Resolved the text Color problem and Header gap problem

client/src/components/Contact.jsx
Reverts Adarsh-Chaubey03/TravelGrid#425
=> Revert "Updated background of Contact page to match Trip Expense Calculator page"

client/src/components/Custom/Navbar.jsx
Reverts Adarsh-Chaubey03/TravelGrid#444
=> Revert "fixed JSX Syntax Error:"

client/package-lock.json, client/package.json, client/src/components/Home/DiscoverSection.jsx, client/src/components/Home/FeatureCards.jsx, client/src/components/Home/FeaturedPackages.jsx, client/src/components/Home/ForumSection.jsx, client/src/components/Home/HeroSection.jsx, client/src/components/Home/Testimonials.jsx, client/src/components/Home/TravelGuides.jsx, client/src/components/Home/TravelTips.jsx
What’s Added:
Created a new TravelTips component to display rotating travel advice for users.
Integrated Framer Motion to add smooth fade and slide transitions between tips.
Tips auto-update every 5 seconds using useState and useEffect.
Responsive and styled card UI for clean display.
📚 Libraries Used:
✅ framer-motion: For animated tip transitions.
Linked Issue:
Closes #433 
GSSOC 2025 Contribution
Everthing is working fine.
=> Feature:Added the Framer Motion in Home Page

client/src/components/TripExpenseCalculator/ExpenseCalculator.jsx
This PR Fixes the issue-457-number-of-people-field-visibility
Fixes #457
=> fixed issue-457-number-of-people-field-visibility

client/src/pages/Dashboard.jsx
=> The dashboard was touching the navbar. Fixed it by adding margin to the top. 

client/src/pages/Dashboard.jsx
Reverts Adarsh-Chaubey03/TravelGrid#465
=> Revert "The dashboard was touching the navbar. Fixed it by adding margin to the top. "

client/src/components/Contact.jsx
Reverts Adarsh-Chaubey03/TravelGrid#467
=> Revert "Changed the background of Contact page"

client/src/components/Contact.jsx
Reverts Adarsh-Chaubey03/TravelGrid#473
=> Revert "Revert "Changed the background of Contact page""

client/src/components/DiscoverCard.jsx, package-lock.json, package.json
Updated the color of the description text to improve visibility and readability. The previous color was too dark and lacked contrast, especially against darker backgrounds, making it hard for users to read comfortably. The new color offers better contrast while still matching the overall design. I have also changed the colour of the text to while when the user will hover and it looks perfectly fine 
before :-
after :-
=> Enhanced Description Colour for Increased Visibility

Server/middleware/auth.js
**Title:**  
Refactor verifyJWT Middleware to Support Header Tokens and Improve Validation
This PR refactors the verifyJWT middleware to make it more robust, concise, and compatible with both web and mobile clients.
🔧 Key Improvements:
✅ Supports JWT token retrieval from both cookies and the Authorization header (Bearer <token>).
✅ Validates presence and format of the token.
✅ Handles token expiration (TokenExpiredError) and invalid tokens (JsonWebTokenError) with proper error messages.
✅ Ensures the decoded token contains a valid userId (id) before proceeding.
✅ Returns consistent and appropriate HTTP status codes (401, 403) for various failure scenarios.
✅ Keeps the middleware logic clean and minimal.
This update ensures better security, broader compatibility, and improved developer and …
=> updated the auth middleware

client/src/components/Custom/Footer.jsx
Centering content of footer section. I have centered the quick links content, and the bulletin were not looking good on centering it so I removed and also for the contact info section I moved the icon above so that the alignment would be more symmetrical.
=> centering footer content 

client/src/App.jsx, client/src/components/Custom/Navbar.jsx, client/src/components/DiscoverCard.jsx, client/src/components/TravelCard.jsx, client/src/context/WishlistContext.jsx, client/src/main.jsx, client/src/pages/PackageDetails.jsx, client/src/pages/Wishlist.jsx
- Integrated "Add to Wishlist" button on the travel package detail page.
- Users can now add or remove packages from their wishlist using context (`WishlistContext`).
- Added conditionally styled button to show "Added to Wishlist" once the package is already added.
- Ensured persistent wishlist data via context state.
- UI feedback improved with visual icon and button text changes.
- Cleaned up minor warnings and improved usability.
https://github.com/user-attachments/assets/6a2416ab-1c25-4b5c-ad5c-a42df99227cc
=> Add Wishlist Functionality 

client/src/components/Custom/Footer.jsx
**Title:**  
Fixed alignment of Footer and center the content in footer section. 
fixes #485 
Before
After
=> Feat:Fix alignment of footer

client/src/pages/TrendingSpots.jsx
Improved Trending Spot page design and layout consistency.
Refactored the design of the Trending Spot page to align it with the overall website theme. Updated font styles, colors, hover effects, and fixed image visibility issues at the bottom of the page.
Fixes #452 
N/A
Updated UI elements to improve visual consistency and user experience.
=> Redesign Trending Spot page design and layout consistency

client/src/components/Custom/Footer.jsx
Fixed footer allignment
Fixes #509 
):
Please dont accept the same all the pull request for same issue
=> [Bug]:fixed footer section

client/package-lock.json, client/package.json, client/src/components/PDF/BookingPDF.jsx, client/src/pages/HotelDetails.jsx
Feature: Booking Confirmation with PDF Download
This PR adds the following enhancements to the Hotel Booking flow:
Booking Confirmation Flow:
Added a "Proceed to Book" button that confirms the booking and generates a unique booking ID using a timestamp + random number format.
PDF Booking Receipt Generation:
Integrated @react-pdf/renderer to allow users to download a customized PDF receipt containing booking details.
PDFDownloadLink UI
Once a booking is confirmed, a "Download Booking PDF" button appears to let users download their personalized booking receipt.
Library-Used:
@react-pdf/renderer – For generating and downloading PDF receipts in React
react-hot-toast – For showing success notifications on booking confirmation
ScreenShots:
Close Issue #434 
All things are Working fine
=> Feature:Booking Hotel PDF Generate

Server/models/hotel.js
**Title:**  
Fixed the Hotel schema
make the necessary fields in hotel schema to be required 
Closes #483
=> fixed hotel schema

client/src/components/Summarizer.jsx
**Title:** fix: center AI Hotel & Flight Review Analyzer and add spacing from navbar/footer
Summary:
- Centered the analyzer card both vertically and horizontally using flex layout with `min-h-screen` to ensure it remains centered across zoom levels.
- Added vertical padding so the card no longer touches the navbar or footer.
- Updated color scheme: switched to a darker background gradient and adjusted card/button colors to blend with the footer/nav (pink accents, subtle borders) for visual consistency.
- Improved accessibility/readability of the summary panel.
Fixes issue: AI Hotel & Flight Review Analyzer page not centered and overlaps with navbar/footer. (#508)
Fixes #508
Before and after comparisons showing:
- original misaligned analyzer box touching navbar/footer
- updated centered …
=> Fixed alignment  of review summarizer for hotel and flight

Server/controller/tripsController.js, Server/index.js, Server/models/trips.js, Server/routes/trips.js, client/src/pages/TravelPlanGenerator.jsx, client/src/pages/TripsPlanned.jsx, client/src/utils/pdfGenerator.js
**Title:**  
✨ Add Dynamic Travel Plan Save, Fetch, Delete & PDF Export Feature
This PR introduces a complete dynamic trip planning feature:
- Users can now generate travel plans using `TravelPlanGenerator.jsx`
- The generated plans are **saved to the database** via `POST /api/trips`
- The `TripsPlanned.jsx` page dynamically **fetches the saved plans** using `GET /api/trips`
- Each trip card has a **Delete** button (`DELETE /api/trips/:id`)
- A **Download as PDF** feature using `jsPDF` is integrated
🔐 **Note:** User-specific trip storage is implemented using `userId`, but **authorization is not enforced** currently because of session/token issues. A separate issue will be opened for that.
Closes #491 
- This PR is intentionally submitted **without login enforcement**, since the …
=> Implement Travel Plan Save, Fetch, Delete & PDF Download Feature

client/src/pages/PackingChecklist.jsx, client/src/pages/Wishlist.jsx
need to fix wishlist UI as text are hidden under Navbar #530
This PR updates the `Wishlist` page to better handle a large number of items. It retains the existing responsive grid layout while ensuring proper padding, spacing, and scroll behavior. This improves the user experience when the wishlist contains many packages.
- Ensured responsive grid for mobile and desktop using Tailwind's grid utilities
- Verified consistent spacing and padding for cleaner layout
- Confirmed that page scroll accommodates large wishlists without layout breaking
- Verified layout on different screen sizes (mobile, tablet, desktop)
- Tested with empty wishlist and long wishlist with 20+ items
None
=> Update: Enhance Wishlist page with pagination and improved styling

Server/config/db.js, client/src/pages/TravelPlanGenerator.jsx, package-lock.json
Description:
This update addresses a bug in the Travel Plan Generator where users could select past dates for travel plans, which is logically invalid. The fix includes:
Date Validation: The date picker now restricts selections to today's date or future dates using the min attribute.
Error Handling: Shows a clear error message if a user manually inputs a past date.
Form Submission Guard: Prevents plan generation if an invalid date is provided.
Impact:
Ensures users can only create travel plans for valid future dates.
Improves user experience by providing clear feedback on date requirements.
Maintains all existing functionality while adding robust date validation.
=> Fix: Prevent Selection of Past Dates in Travel Plan Generator

Server/controller/updateProfileController.js, Server/index.js, Server/middleware/protectMiddleware.js, Server/middleware/uploadMiddlware.js, Server/routes/userRoutes.js, client/src/components/Custom/Navbar.jsx, client/src/context/AuthContext.jsx, client/src/pages/Dashboard.jsx
**Title:**  
Fixed Profile Update Functionality (Completed Backend Integration)
Implemented and integrated the backend for the profile update feature. Now users can successfully update their name, email, and profile picture, and the changes reflect both on the frontend and in local storage.
Fixes #521 , Closes #521 
- Before Changes
- After Changes
Added PUT /api/users/:id route to handle profile updates and improved AuthContext with a proper updateUser function to sync updated data.
=> Profile updating implementation

Server/package-lock.json, Server/package.json, client/src/components/Custom/Navbar.jsx, client/src/components/Home/HeroSection.jsx, client/src/context/ThemeContext.jsx
**Title:**  
- [X ] Bug fix
- [✔️ ] My code follows the project style guidelines
- [✔️  ] I have performed a self-review of my code
- [✔️  ] My changes generate no new warnings or errors
=> Fix: Navbar & Hero in light mode and make dark mode default #573

client/src/components/DiscoverCard.jsx, client/src/components/Home/FeatureCards.jsx, client/src/components/Home/FeaturedPackages.jsx, client/src/components/Home/ForumSection.jsx, client/src/components/Home/Testimonials.jsx
**Title:**  
- [ x] Bug fix
- [ x] My code follows the project style guidelines
- [x ] I have performed a self-review of my code
- [ x] My changes generate no new warnings or errors
=> Fix: Text Blurs in Light Mode on Hover. #582

client/src/pages/Hotels.jsx
**Title:**  
Fixed Footer.
#587
=> Footer Rendered Twice

client/src/components/DiscoverCard.jsx, client/src/components/Home/DiscoverSection.jsx
**Title:**  
style: improve DiscoverCard and DiscoverSection UI"
- Improved UI styling for DiscoverCard and DiscoverSection components
- Fixed inconsistent card heights and added hover effects
- Enhanced responsiveness for different screen sizes
Fixes #589 , Closes #589 -->
=> style: improve DiscoverCard and DiscoverSection

client/src/pages/TicketBooking.jsx
**Title:**  
Add different dropdown options
Provided various dropdown options for various transportation options that are available in the application.
Closes #593
=> Add different dropdown options

client/src/components/DiscoverCard.jsx
Improvements made :
Center-aligned both title and description with slight gap in between them
Changed text color to white.
Added padding to the paragraph for better spacing.	
Extra spacing (mb-4) between image and content.
All text now centered.
All changes to file DiscoverCard.jsx
=> issue #531 Destination Card text improvement

client/src/components/NewQuestionModal.jsx, client/src/pages/TravelForum.jsx
**Title:**  
This PR transforms the Travel Forum from a static page with a placeholder "Feature coming soon" button into a fully functional community forum where users can ask and interact with travel-related questions.
- **Complete NewQuestionModal component** with form validation and real-time error handling
- **Enhanced Travel Forum page** with advanced search, filtering, and sorting capabilities
- **Real-time question posting** with immediate UI updates and smooth animations
- **Category-based organization** with 8 specialized travel categories
- **Professional dark/light theme integration** matching the existing site design
- Custom styled scrollbars with gradient themes for better UX
- Glassmorphism design effects with backdrop blur
- Form validation with character limits and visual …
=>  ✨ Implement Ask New Question functionality for Travel Forum

client/src/components/recommendation.jsx
Reverts Adarsh-Chaubey03/TravelGrid#671
=> Revert "Sadhvikesarwani/607"

client/src/components/Custom/Navbar.jsx, client/src/components/Home/HeroSection.jsx
This PR fixes the issue where logged-in users were unable to use the search feature due to an incorrect login session check.  
Previously, even after signing in, a popup appeared stating:
> "You must sign in to search places."
This bug has been resolved, ensuring that logged-in users can now interact with the search input without being prompted to log in again.
- Fixed the session validation logic to correctly recognize active user login sessions in the search functionality.
- Removed unnecessary popup triggers for logged-in users.
- Logged in as a user and confirmed that the "sign in" popup no longer appears when searching.
- Verified that the search button is clickable for logged-in users.
I would like to work on implementing **the actual search functionality** in the next issue to …
=> Fix: Resolve session persistence issue in search functionality for logged-in users

client/package-lock.json, client/src/pages/PackageDetails.jsx
Description:
Fixed the floating bar overlap issue by adjusting positioning from absolute to relative so it no longer covers the package description.
Centred the package description text using Tailwind’s text-centre class for better readability.
Changes Made:
Updated floating bar layout to flow naturally without overlap.
Applied text-centred styling to the description paragraph.
Result:
The floating bar now aligns properly and does not block any content.
Description is neatly centred for a cleaner UI.
Screenshot:
=> Overlay fixed

client/src/components/Custom/Footer.jsx, client/src/components/Custom/Navbar.jsx, client/src/pages/TravelGuidesProfiles.jsx
**##Description**
Added the site logo to both the navbar and the footer for consistent branding. Also changed the background color of the guide card because it previously matched the page background, making it hard to see.
**## Type of Change**
**## Checklist**
=> Add logo to navbar and footer, update guide card background color

client/src/components/Custom/Footer.jsx, client/src/components/Custom/Navbar.jsx, client/src/components/Home/FeatureCards.jsx, client/src/components/Home/HeroSection.jsx, client/src/pages/currencyconverter.jsx, currency-wallet.html
**Title:**  
Added Multi-Currency Travel Wallet
This update adds a Multi-Currency Travel Wallet feature to TravelGrid.
It allows users to select their home and target currencies, enter an amount, and instantly view the converted value — even when offline — by using a built-in currency rate table.
This enhancement improves convenience for travelers in low or no-connectivity situations.
Fixed Issue
Addresses the lack of a built-in currency conversion feature in TravelGrid.
Issue Number #648
=> Multi-Currency Travel Wallet

client/src/data/PackageData.js
**Title:**  
Made FAQ section more informative
The FAQs section previously contained only one question, which limited its usefulness. This PR adds multiple relevant FAQs to address common queries about the trip/package, improving user understanding and decision-making.
Content Update
Fixes #669 
Had limited FAQs. For example: this is the Bali Bliss package
**(Before)**
**(After)**
=> Fix: FAQ Section made more informative

client/src/components/TravelTips.jsx
- Added collapsible **Travel Tips** card to the homepage.
- Included sample tips for Mumbai (UI only; no backend API call).
- Styled to match the existing TravelGrid theme.
Closes #564
=>  add Travel Tips UI to homepage (frontend-only, no server changes)

client/src/main.jsx, client/src/pages/Wishlist.jsx
Reverts Adarsh-Chaubey03/TravelGrid#754
=> Revert "Update Wishlist page background to a light gradient theme"

client/src/components/Custom/Navbar.jsx
=> Merged PetGuide into tools

client/package-lock.json, client/package.json, client/src/pages/Wishlist.jsx
Reverts Adarsh-Chaubey03/TravelGrid#755
=> Revert "Enhanced Wishlist UI"

client/src/components/Chatbot.jsx
Improve textarea padding and send button UI in Chatbot for better user experience
-  Reduce padding and hide scrollbar in textarea for better UX and a cleaner look on long input.
- Update button styles for consistent rounded shape and changed color scheme for better visibility.
- Improve vertical alignment and spacing to maintain design consistency.
- Add cursor pointer to buttons  for better interactivity
Fixes #751 
N/A
Improves UI for the chatbot input and buttons to make them cleaner, more consistent, and easier to use.
=> Refactor Textarea and Button UI Travel Assistant bot for improved user experience

client/src/components/Home/DiscoverSection.jsx
This PR implements the filter, search, and sort features in the application.
Additionally, it removes an accidental nested Git repository located in client/TravelGrid to ensure a clean project structure.
Filter: Users can filter items based on selected criteria (e.g., category, type, or other attributes).
Search: Implemented keyword-based search to quickly find matching items.
Sort: Added sorting options (e.g., alphabetical, price, or date) for better organization of results.
=> Add filter, search, and sort functionality; remove nested git repo from client folder

client/src/components/Custom/Navbar.jsx, client/src/components/TravelCountdownTimer/CountdownSettings.css, client/src/components/TravelCountdownTimer/CountdownSettings.jsx, client/src/components/TravelCountdownTimer/CountdownTimer.css, client/src/components/TravelCountdownTimer/CountdownTimer.jsx, client/src/components/TravelCountdownTimer/DailyTravelTips.css, client/src/components/TravelCountdownTimer/DailyTravelTips.jsx, client/src/components/TravelCountdownTimer/README.md, client/src/components/TravelCountdownTimer/SocialSharing.css, client/src/components/TravelCountdownTimer/SocialSharing.jsx, client/src/components/TravelCountdownTimer/TravelCountdownTimer.css, client/src/components/TravelCountdownTimer/TravelCountdownTimer.jsx, client/src/components/TravelCountdownTimer/index.js, client/src/index.css, client/src/main.jsx, client/src/pages/CountdownDemo.jsx, client/src/pages/Dashboard.jsx, client/src/pages/TripsPlanned.jsx
**Title:**  
Implement Travel Countdown Timer with Daily Tips and Social Sharing
This pull request implements a comprehensive Travel Countdown Timer feature that enhances user engagement and excitement for upcoming trips. The feature includes real-time countdown displays, daily travel tips, social media integration, trip reminder system, and customizable countdown themes. This implementation addresses the requirements outlined in issue #1 and integrates seamlessly with the existing trip management system.
Fixes #767 
1. **Trip Countdown Display**: Real-time countdown with days, hours, minutes, and seconds
2. **Daily Travel Tips**: Curated tips that change daily based on countdown progress
3. **Social Media Integration**: Share countdown status on Twitter, Facebook, and Instagram
4. **Trip …
=> Implement Travel Countdown Timer with Daily Tips and Social Sharing

ENHANCED_CURRENCY_CONVERTER_README.md, IMPLEMENTATION_SUMMARY.md, Server/CURRENCY_SETUP.md, Server/index.js, Server/package-lock.json, Server/package.json, Server/routes/currencyRoutes.js, client/src/components/Custom/Navbar.jsx, client/src/components/TravelCountdownTimer/CountdownSettings.css, client/src/components/TravelCountdownTimer/CountdownSettings.jsx, client/src/components/TravelCountdownTimer/CountdownTimer.css, client/src/components/TravelCountdownTimer/CountdownTimer.jsx, client/src/components/TravelCountdownTimer/DailyTravelTips.css, client/src/components/TravelCountdownTimer/DailyTravelTips.jsx, client/src/components/TravelCountdownTimer/README.md, client/src/components/TravelCountdownTimer/SocialSharing.css, client/src/components/TravelCountdownTimer/SocialSharing.jsx, client/src/components/TravelCountdownTimer/TravelCountdownTimer.css, client/src/components/TravelCountdownTimer/TravelCountdownTimer.jsx, client/src/components/TravelCountdownTimer/index.js, client/src/index.css, client/src/main.jsx, client/src/pages/CountdownDemo.jsx, client/src/pages/Dashboard.jsx, client/src/pages/EnhancedCurrencyConverter.jsx, client/src/pages/TripsPlanned.jsx, client/src/pages/currencyconverter.jsx, client/src/services/currencyService.js, client/vite.config.js, test-currency-api.js
**Title:**  
Implement Enhanced Currency Converter with Real-time Rates, Expense Tracking, and Travel Insights
This pull request implements a comprehensive **Enhanced Currency Converter** feature that provides real-time exchange rates, historical currency trends, intelligent travel expense calculations, and smart travel recommendations. The feature addresses the requirements outlined in issue5.md and significantly enhances the TravelGrid application's financial planning capabilities for international travelers.
- **Real-Time Exchange Rates**: Integration with ExchangeRate-API supporting 170+ world currencies
- **10-Minute Auto-Update**: Smart rate refresh system with countdown timer and manual refresh option
- **Advanced Conversion**: Multi-currency conversion with historical trend charts …
=> Enhanced currency converter

client/src/pages/Hotels.jsx
**Title:**  
improved spacing, misalignment and gap between items.
This pull request addresses the UI spacing and alignment issues reported in Issue #774. Specifically, it improves the following:
- Increased spacing between the heading and the navbar to avoid crowding and improve visual hierarchy.
- Corrected misalignment of heading and related elements for a more balanced and polished layout.
- Added consistent gaps between items to enhance readability and overall UI aesthetics.
- These adjustments contribute to a cleaner, more user-friendly interface consistent with the design guidelines.
Fixes issue: #774 
Before--
After--
Improved heading spacing and alignment with navbar, added consistent gaps between items for better UI clarity and responsiveness.
=> improved spacing, misalignment and gap between items

client/src/components/TripExpenseCalculator/ExpenseCalculator.jsx, client/src/index.css
**Title:**  
Enhance the UI/UX of the expense calculator form
This PR improves the visual design and user experience of the Trip Expense Calculator form. It adds a smooth gradient background with subtle blur and shadow effects to make the form stand out and look more polished. The input fields now feature a clean bottom border that changes color on focus, giving clear visual feedback to users. Overall, the styling has been updated to match the website’s theme, resulting in a more cohesive and appealing interface.
Fixes Issue: #776 
Before--
After--
=> Enhance the UI/UX of the expense calculator form

client/src/pages/TrendingSpots.jsx
**Title:**  
Fix the favorite button in the Trending Spots page.
When the user clicks on the favorite button, the place is marked as favorite.
Closes #784
=> Fix the favorite button in Trending Spots page

client/src/pages/TravelGuidesProfiles.jsx
Title:
Fix Content Visibility Issue in Travel Guide Cards (Light Mode)
This PR resolves a visibility issue in Travel Guide cards when viewed in Light Mode. It improves text contrast, background shading, and interactive element clarity to meet accessibility standards.
Changes:
- Updated text and background colors for better contrast
- Improved hover/focus states
- Verified responsiveness and theme consistency
Closes #718
=> Fix content visibility in Travel Guide cards for Light Mode

client/.gitignore, client/package-lock.json, client/package.json, client/src/components/Custom/Navbar.jsx, client/src/components/TravelPlanGenerator/AIIteraryBuilder.jsx, client/src/components/TravelPlanGenerator/AIPlanningInterface.jsx, client/src/components/TravelPlanGenerator/AIRecommendationEngine.jsx, client/src/components/TravelPlanGenerator/AITravelPlanner.jsx, client/src/components/TravelPlanGenerator/PredictiveAnalytics.jsx, client/src/components/TravelPlanGenerator/README.md, client/src/components/TravelPlanGenerator/SmartBudgetOptimizer.jsx, client/src/components/TravelPlanGenerator/index.js, client/src/main.jsx, client/src/pages/AITravelPlannerDemo.jsx
**Title:**  
Implement AI-Powered Travel Planner with Advanced Machine Learning Algorithms and Intelligent Itinerary Generation
This pull request implements a comprehensive **AI-Powered Travel Planner** feature that leverages advanced machine learning algorithms to provide personalized travel recommendations, intelligent itinerary generation, and predictive travel insights. The feature addresses the requirements outlined in issue5.md and significantly enhances the TravelGrid application's travel planning capabilities with sophisticated AI-driven intelligence.
- **Intelligent Itinerary Generation**: AI-driven itinerary creation based on destination, duration, and user preferences
- **Advanced Recommendation Engine**: Machine learning-based attraction and restaurant recommendations
- …
=>  AI-Powered Travel Planner

client/src/index.css, client/src/pages/Wishlist.jsx
**Title:**  
redesigned the wishlist page
This pull request revamps the Wishlist page to align with the overall theme of the website. Changes include improved spacing, consistent typography, background updates, and refined color schemes to ensure a cohesive look and feel across the platform. The design now blends seamlessly with the site's aesthetic, enhancing user experience and visual appeal.
Fixes Issue: #806 
Before--
After--
=> redesigned the wishlist page

client/src/components/Home/DiscoverSection.jsx
**Title:**  
Removed search bar & filter from Discover New Destination
I have Removed Search bar & filter from Discover New Destination. Also adjusted all 4 cards in same row.
- [ 795] Bug fix
Fixes #795 , Closes #795
=> Removed search bar & filter from Discover New Destination

client/src/components/Custom/Footer.jsx
**Title:**  
Fixed path to the latest currency converter
This PR fixes the link in the footer section, which was earlier taking the user to an outdated currency converter page. But now it is taking the user to the updated currency converter page.
fixed #821
=> Fixed path to the latest currency converter

client/src/pages/BookingHistory.jsx
=> Update the theme of booking history

client/src/pages/Privacypolicy.jsx
**Title:**  
Fix: Update Privacy Policy heading styles for dark mode
Updated the Privacy Policy page heading styles to improve visibility in dark mode. Adjusted text color and ensured proper contrast for better readability and consistent UI across light and dark themes.
Closes #888 
This fix addresses readability issues for the heading in dark mode and ensures visual consistency throughout the application.
=> Fix: Updated Privacy Policy heading styles for dark mode

client/src/pages/Hotels.jsx
**Title:** 🐞 Bug Fix: Search Bar Text Not Visible in Hotels.jsx
Fixed an issue in `Hotels.jsx` where the search input text was not visible after typing.  
The problem was due to insufficient text color contrast with the background.  
Updated the input field style to use `text-black` for better readability.
Fixes #911 
None
=> Fix the text color in the search box

client/src/pages/DestinationPacking.jsx, package-lock.json, package.json
**Title:**  
Redesigned the **Destination Packing** page to improve **UI/UX**.
- Modern **gradient header** and improved input/button styles.
- Improve spacing of heading
- just change the UI/UX 
- Cleaner, responsive **packing category cards** with shadows and spacing.
Improves readability, interactivity, and overall user experience for travelers.
Fixes Issue: #934 
Before--
After--
=> Redesigned the Destination Packing page to improve **UI/UX**.

client/src/pages/CountdownDemo.jsx, client/yarn.lock
**Title:**  
Removed unrelated text and non-functional buttons above the footer in the travel countdown timer page.
Removed unnecessary and unrelated text and non-functional buttons from the CountdownDemo.jsx file to provide a cleaner UI to the user.
Closes #902
=> Removed unrelated text and non-functional buttons above the footer in the travel countdown timer page

client/src/components/TravelPackingChecklist/PackingChecklist.jsx, client/src/components/TripExpenseCalculator/ExpenseCalculator.jsx, client/src/components/TripExpenseCalculator/ExpenseInputRow.jsx, client/src/pages/PackingChecklist.jsx, client/src/pages/PetTravel.jsx, client/src/pages/TripCalculator.jsx
=> fix functions

client/src/components/FluidCursor.jsx, client/src/pages/BookingHistory.jsx, client/src/pages/Hotels.jsx
Reverts Adarsh-Chaubey03/TravelGrid#954
=> Revert "Fix: Fluid Cursor Overlapping UI Elements (UI/UX Improvement)"

client/src/pages/PetTravel.jsx
**Title:**  
UI/UX Enhancement for Multiple Pages (Majorly Light mode) 
- Fixed light theme for Pet Travel
- Fixed light theme for Expense Calculator
- Fixed light theme for Checklist
Fixes #858
=> UI/UX Enhancement for Multiple Pages (Majorly Light mode) 

client/src/pages/LocationDetail.jsx
=> Added a Book Now button in saved destination 

client/src/components/Custom/CustomCarousel.jsx
This PR enhances the `CustomCarousel` component with:  
- **Navigation Dots** → Dots placed below the cards, centered for a clean look.  
- Active dot highlights the current slide.  
- Clicking on a dot directly navigates to the respective card.  
- **Movable Carousel Functionality** → Smooth transition between slides using:  
- Left/Right buttons  
- Auto-slide interval  
- Navigation dots for quick access  
These changes improve **usability and control** without altering the existing design.  
Closes #962  
https://github.com/user-attachments/assets/06b89f88-405c-4fa6-ab3a-601e668447a0
=> feat(carousel): add navigation dots & enhance movable carousel experience

client/src/pages/HotelBookingForm.jsx
**Title:**  
Add Date of Birth Input
I have added the date of birth Input in the hotel booking page and tested the booking
Closes #967
=> Add Date of Birth Input

client/src/components/Custom/Navbar.jsx, client/src/pages/Music.jsx, client/src/pages/TravelGuidesProfiles.jsx
**Title:**  
Enhanced Music page according to theme of website
Enhanced the Music page UI to better match the overall theme of the website.  
Updated styling, colors, and layout for a more consistent and visually appealing experience in both light and dark modes.
- Improved hero section styling and spacing for music items
- Updated color scheme to align with the website theme
- Ensured responsiveness across different screen sizes
- fixes to hover and button interactions
- added cursor pointer when hiver on buttons
- add borders on hovering (pink color)
---
Fixes Issue: #978 
Before--
After--
and hovering effect you can see on browser
=> Enhanced Music page according to theme of website

client/src/components/Custom/Navbar.jsx, client/src/pages/TravelGuidesProfiles.jsx, client/src/pages/VisaChecker.jsx
**Title:**  
Redesign Visa & Travel Requirements Page to Match Website Theme
This PR updates the Visa & Travel Requirements page to align with the overall theme and styling of the website. Key enhancements include:
- Applied a modern gradient background that complements the site's color palette.
- Redesigned layout for better readability and user experience.
- Updated typography and spacing for improved visual hierarchy.
- Ensured responsive design across all screen sizes.
- Integrated dark mode support consistent with the rest of the website.
These changes make the page visually cohesive with the rest of the site while improving usability and accessibility.
Fixes Issue: #989 
Before--
After--
=> Redesign Visa & Travel Requirements Page to Match Website Theme

client/src/components/TravelPlanGenerator/AIIteraryBuilder.jsx, client/src/components/TravelPlanGenerator/AIPlanningInterface.jsx, client/src/components/TravelPlanGenerator/AIRecommendationEngine.jsx, client/src/components/TravelPlanGenerator/PredictiveAnalytics.jsx
**Title:**  
Revamped all 5 pages of **AI Travel Planner** with major improvements:  
- 🎨 Modern and consistent UI redesign  
- 🌈 Applied gradient-based color palette and improved visuals  
- 📱 Enhanced responsiveness for all screen sizes  
- ⚡ Optimized navigation flow and loading speed  
- 🔍 Improved readability and typography consistency  
- 🧭 Better component structure for maintainability  
- 🎯 Aligned design with overall project theme  
Fixes Issue: #1047 
Before--
After--
=> Revamp: All 5 Pages of AI Travel Planner

client/src/App.jsx, client/src/components/Custom/Navbar.jsx, client/vite.config.js
Reverts Adarsh-Chaubey03/TravelGrid#1062
=> Revert "feat: add tooltip for package language in TravelCard"

client/src/pages/Privacypolicy.jsx, client/yarn.lock
Description
This PR updates the Privacy Policy page UI to improve readability and user experience. The changes include layout adjustments, typography improvements, and better spacing for a clean and consistent design.
Type of Change
New feature (UI enhancement)
Checklist
My code follows the project style guidelines
I have performed a self-review of my code
I have commented my code, particularly in hard-to-understand areas
My changes generate no new warnings or errors
Related Issues
Closes #1065
Additional Notes
Improved overall design consistency.
Ensures better readability across devices.
https://github.com/user-attachments/assets/51d8718e-8dbd-461b-8e30-7b6c545960ae
=> Enhance Privacy Policy Page UI

client/src/index.css
=> fix cls score to 0.01

client/src/components/TravelPackingChecklist/PackingChecklist.jsx
**Title:**  
Mobile Responsiveness & Feature Enhancements for Travel Packing Checklist
Fixes: _On mobile devices, the Travel Packing Checklist page had multiple responsiveness problems_  
**Path:** `Navbar -> Tools -> Travel Packing Checklist`
Original issues:
- Checklist items were not visible on mobile view.
- "Add Item" and "Add Section" buttons were overflowing their container.
- Too many action buttons (Export, Reset, Clear, etc.) cluttered the layout on smaller screens.
- Sections list consumed too much vertical space.
- No search functionality to quickly filter checklist items.
---
- Checklist items are now **visible immediately** on mobile view.
- **Add Item / Add Section** buttons are responsive and properly contained.
- All secondary actions (Export, Reset, Clear, etc.) are …
=> Added Mobile Responsiveness for Page:Packing Checklist

client/src/pages/TicketBooking.jsx
**Title:**  
Enhance Ticket Page theme colors and visibility.
On the Ticket Page:
- Updated background color in Light/Dark Mode for better readability.
- Improved background image visibility (reduced opacity/whiteness).
- Updated icons and badges border, background, and text colors to match theme consistency.
- Updated input field background color and border color to match theme consistency.
- Updated input icons size to match other icons size for consistency.
- Added cursor pointer for improving user experience.
Closes #1061 
Updated Dark mode :
Updated Light mode :
N/A
=> Enhance Ticket Page theme colors and visibility

client/src/components/Custom/Footer.jsx, client/src/components/Home/FeatureCards.jsx, client/src/components/Home/Testimonials.jsx, client/src/pages/TrendingSpots.jsx
=> New branch

Server/.env.example, client/src/.env.example
**Title:**  
add env example files
Added the missing `.env.example` files in both frontend and backend
Fixes #1117
=> add env example files

client/src/pages/GitHubStats.jsx
**Title:**  
enchance project stats
Added the `Yesterday` or `Today` in the project last commit alongside with the date
Fixes #1118
=> enchance project stats

client/src/components/Custom/Footer.jsx
**Title:**  
This pr adds email validation check
Used regex to check if an email is valid or not
Fixes #1110
=> add email validation

client/package-lock.json, client/src/components/Custom/CustomCarousel.jsx, client/src/components/Custom/styles/CustomCarousel.css, client/src/pages/GitHubStats.jsx, client/yarn.lock
**Title:** Fix guide card styling inconsistency and improve visual appearance on home page
Fixed the guide cards on the guides page that were appearing lighter and inconsistent. Updated the card styling to provide better visual consistency across different theme modes and improved the overall appearance with proper backdrop blur effects, border styling, and hover states.
Fixes #1124 
- Cards appeared lighter and inconsistent
- Poor visual hierarchy between light and dark modes
- Consistent card styling across themes
- Better backdrop blur and border effects
- Improved hover states and visual feedback
- Enhanced backdrop blur effects for better glassmorphism appearance
- Improved conditional styling for dark/light theme modes
=> Fix guide card styling inconsistency and improve visual appearance on home page

client/src/components/Custom/Footer.jsx
=> email in footer is clickable

client/package-lock.json, client/src/pages/TravelForum.jsx, client/yarn.lock
**Pull Request about:**   Changing the font color of Reply Button
This pull request standardizes the font color of the Reply button in the Forum section to ensure UI/UX consistency. The change addresses the issue where the Reply button had inconsistent font colors across different forum posts, leading to a less cohesive user experience.
-  UI/UX fix
=> Fix: standardize Reply button font color in Forum section

client/src/pages/TravelForum.jsx
**Title:**  
fix(ui): make Close & Submit button font color consistent in Dark Mode
This PR fixes inconsistent font colors for the Close and Submit buttons in Dark Mode to align with the design system for readability and UI consistency.
- [ x ] Bug fix
- [ x ] My code follows the project style guidelines
- [ x ] I have performed a self-review of my code
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [ x ] My changes generate no new warnings or errors
Connected to issue: #1161
=> fix(ui): make Close & Submit button font color consistent in Dark Mode

client/src/pages/TrendingSpots.jsx
**Title:**  
Improve Trending Spots Page theme, colors, and spacing.
This PR updates the theme and layout of the Trending Spots Page : 
- Fix the layout issue by adding margin in main heading. 
- Changed the main background color for better design and contrast.
- Updated the image overlay background and opacity based on light/dark theme.
- Refined filter bar, stats banner cards, and destination cards with updated text, border, and background colors.
- Added cursor pointer to all clickable buttons.
Closes #1168 
Dark mode:
Light mode:
N/A
=> Enhance: Trending Spots page theme and fix layout issues

client/src/pages/TrendingSpots.jsx
**Title:**  
Added social media sharing feature for trending spots
Added sharing option for trending spots using share intent of social medias
- [✔️] New feature
- [✔️] My code follows the project style guidelines
- [✔️] I have performed a self-review of my code
- [✔️] I have commented my code, particularly in hard-to-understand areas
- [✔️] My changes generate no new warnings or errors
Close #1192 
share on X -
=> Added social media sharing feature for trending spots

client/src/pages/TrendingSpots.jsx
Reverts Adarsh-Chaubey03/TravelGrid#1202
=> Revert "Added social media sharing feature for trending spots"

client/src/components/FeedbackButton.jsx, client/yarn.lock
**Title:**  
Fixed share feedback text on hover issue 
While the feedback button on hover a share feedback text appears and vanishes within fraction of seconds and is getting over-riden by the chatbot button which is making users to read and understand what is written due to it's active time period.
##Solution
Instead of enabling another text element on button hover, I made the enhancement as the button with icons turns into button with share feedback text upon hover which is much more user experience friendly.
Fixes #1197
=> Fixed share feedback hover issue

Server/index.js
**Title:**  
Signup failed issue resolved #1196
- Initially the user was not able to signup even with legit email address. 
- After resolving the mapping issue between server and signup page the issue is resolved now.
#1196 
The image of account verification page after proper working of signup form.
=> Signup failed issue resolved #1196

client/src/components/Home/FeedbackReviews.jsx, client/src/pages/Home.jsx
Title:
Add Feedback & Reviews Section Above Footer
Description:
- This PR adds a Feedback & Reviews section above the footer 
- Implemented a form with an input field and a submit button.
- After submission:
- The feedback is displayed dynamically below the form.
- A success message is shown: “Submitted successfully! Thank you for your feedback.”
- Styled the section using CSS to match the overall site theme.
- This feature enhances user interaction and provides valuable insights from visitors.
Type of Change
- Bug fix
- New feature✅
- Refactor
- Documentation update
- Other (please describe):
Checklist:
- ✅My code follows the project style guidelines
- ✅I have performed a self-review of my code
- ✅I have commented my code, particularly in hard-to-understand areas
- ✅My changes generate …
=> Add Feedback & Reviews Section Above Footer in homepage

Server/controller/authController.js, Server/index.js, Server/test-email.js, Server/utils/emailService.js
**Title:**  
User not getting OTP after signUp for email verification. #1213 
After creating account in the the site user is getting redirected to OTP form to verify the user mail id. However the user was not getting any kind of OTP email to verify and continue.
Fixes #1213
=> User not getting OTP issue resolved.

Server/.env.example, Server/package-lock.json, client/package-lock.json, client/yarn.lock
This PR sets up the backend for **Level 3 - TravelGrid** with a proper MongoDB connection and Express server configuration.
- Added `dotenv` configuration to manage environment variables.
- Established a MongoDB connection using `MONGODB_URI` from `.env`.
- Implemented error handling for failed DB connections.
- Created a basic Express server with JSON middleware.
- Added a root (`/`) route returning a health-check message.
- Configured project to respect `.env` and `.gitignore`.
1. Run `npm install` to install dependencies.
2. Create a `.env` file in the root with the following:
MONGODB_URI=mongodb://localhost:27017/travelgrid
PORT=5000
JWT_SECRET=your_jwt_secret_here
3. Start the server:
```bash
npm run dev
4.Visit http://localhost:5000/ → should return "🚀 TravelGrid API is running...". …
```
=> [Level 3] Setup MongoDB connection and Express server

client/src/App.jsx, client/src/components/Breadcrumbs/Breadcrumbs.jsx, client/src/components/TripExpenseCalculator/ExpenseCalculator.jsx, client/src/components/TripExpenseCalculator/ExpenseChart.jsx, client/src/components/TripExpenseCalculator/ExpenseInputRow.jsx, client/src/pages/LocationDetail.jsx, client/src/pages/TrendingSpots.jsx, client/src/pages/currencyconverter.jsx
**Title:**  
Added Breadcrumb feature for smooth navigation
implemented breadcrumb to navigate from one page to another page
- [✔️] New feature
- [✔️] My code follows the project style guidelines
- [✔️] I have performed a self-review of my code
- [✔️] I have commented my code, particularly in hard-to-understand areas
- [✔️] My changes generate no new warnings or errors
Close #1205
Breadcrumb in dark mode
At home page
in light mode
=> Added Breadcrumb feature for smooth navigation

README.md
Fixes: #1217
Improved the README.md file for the TravelGrid project by enhancing clarity, structure, and visual appeal. Added:
- Engaging project overview with emojis for better readability  
- Clear and detailed prerequisites section with helpful icons  
- A troubleshooting table for common setup issues  
- Comprehensive contributing guidelines with step-by-step instructions  
- Project admin contact information with direct profile links  
These improvements aim to provide contributors and users with a better understanding of the project, making onboarding smoother and collaboration easier.
---
Please merge this pull request.
=> Fixed : Enhance README.md for TravelGrid

client/src/pages/PackageDetails.jsx
**Title:**  
Enhance: Improve text visibility, background gradient, and text colors on Book Now page
This PR improves the UI of the Book Now page by:
- Enhancing text visibility in both light and dark modes.
- Updating the background gradient for better contrast with the main background.
- Adjusting some text colors for consistency and readability.
- Added cursor-pointer and transitions to clickable buttons.
- Adding a gradient overlay on the image for better visual depth.
- Refining border colors for consistency across themes.
- Changed icons colors to align with the overall design.
Fixes #1239  
N/A
N/A
=> Enhance : Improve Book now text visibility, colors and  background gradient

client/src/pages/TicketBooking.jsx, client/src/pages/TravelPlanGenerator.jsx, client/src/pages/VisaChecker.jsx
**Title:**  
Make date icon theme responsive
This pull request updates the styling of the date icon to make it fully responsive. The changes ensure that the icon adjusts correctly in both light and dark modes, improving the overall UI consistency.
Fixes #1247
No breaking changes introduced. Only styling improvements were made.
=> Make date icon theme responsive

client/src/App.jsx, client/src/pages/About.jsx
=> removed the extra scroll bar in the About page

client/src/pages/LocationDetail.jsx
fixes #1317
- removed unnecessary overview tab
- added a functionality of toggling in the photos tab
- made the UI cleaner
=> Removed the overview button from the location page of the trending spot

client/src/components/Custom/Navbar.jsx, client/src/main.jsx, client/src/pages/Rentals.jsx
=> Created Rental Page from scratch

client/src/components/Home/HeroSection.jsx
=> Removed the Currency Converter from the home page 

client/src/components/Home/HeroSection.jsx, client/src/pages/Rentals.jsx
=> Revamped the margin in the hero section of rentals page in Support

client/src/components/Contact.jsx
Reverts Adarsh-Chaubey03/TravelGrid#1352
=> Revert "Fix: remove overriding background color in Contact "

client/src/components/CustomItenary.jsx
fixes #1349 
- made the background of the page similar to the website theme
- enhanced UI ,UX
=> fixed the Custom iternary page in both light and dark modes

client/src/pages/Terms&Conditions.jsx
=> Fixed Inconsistency for terms of service page in Both Theme

client/src/main.jsx, client/src/pages/BikeDetail.jsx, client/src/pages/Rentals.jsx
=> Created Bike Rental Detail Page on "Book Now" Click with Full Bike Info, Booking & Guidelines

Server/.env.example, Server/config/db.js, client/src/context/AuthContext.jsx
**Related Issue**
- Closes #1397
**Summary of Changes**
This Pull Request addresses the **Unable to Create Account — Network Error (#1397)** by fixing incorrect client-side API endpoints and enhancing the server's MongoDB connection robustness.
**Key Changes:**
1.  **API Base URL Correction:** Changed the client's API base URL from the incorrect endpoint (`http://localhost:5000/api/v1`) to the actual server mount point (`http://localhost:5000/api`). This fixes network errors for signup, login, and user fetch.
2.  **Logout HTTP Verb Correction:** Aligned the logout API call to use the correct HTTP verb expected by the server:
* From: `POST /api/auth/logout`
* To: `GET /api/auth/logout`
1.  **Robust DB Connection:** Updated the connection logic to check for either the `MONGO_URI` or …
=> Fix: Resolve Account Creation Network Error (#1397) and Enhance DB Connection

client/src/components/Custom/Footer.jsx, client/src/pages/TravelForum.jsx
Closes: https://github.com/Adarsh-Chaubey03/TravelGrid/issues/1380
> Refactored TravelForum page for better readability, improved error handling in data fetching, and enhanced the search/filter UI with new styles and layout adjustments.
=> Update improve TravelForum UI
